language: php

php:
  - 7.3

before_script:
  - echo 'GH_TOKEN='$GHTOKEN > .env
  - echo 'SLACK_TOKEN='$SLACKTOKEN >> .env
  - echo 'SLACK_CHANNEL='$SLACKCHANNEL >> .env
  - composer install

script:
  - php bin/console slack:notifier