name: Slack Notifier

on:
  schedule:
    - cron:  '0 7 * * 1-5'
#  push:
#    branches:
#      - master

jobs:
  slacknotifier:
    runs-on: ubuntu-latest
    name: Slack Notifier
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      -   uses: actions/checkout@v2

      -   name: Download Stats for QA
          uses: benday-inc/download-latest-artifact@main
          with:
            token: ${{ secrets.GH_TOKEN_WITH_PERMISSIONS }}
            repository_owner: 'PrestaShop'
            repository_name: 'presthubot'
            workflow_name: 'Slack Notifier'
            branch_name: 'master'
            download_path: '${{ github.workspace }}/temp'
            download_filename: 'artifact.zip'

      -   name: Unzip artifact
          uses: montudor/action-zip@v0.1.1
          with:
            args: unzip -qq temp/artifact.zip -d .cache

      -   name: Display cache for debugging
          run: cat .cache/slacknotifier_checkStatsQA.json
          continue-on-error: true

      -   name: Composer install
          run: composer install --ansi --prefer-dist --no-interaction --no-progress --quiet

      -   name: Write env file
          run: |
              echo 'GH_TOKEN='${{ secrets.GH_TOKEN }} > .env && \
              echo 'SLACK_TOKEN='${{ secrets.SLACK_TOKEN }} >> .env && \
              echo 'SLACK_CHANNEL_CORE='${{ secrets.SLACK_CHANNEL_CORE }} >> .env && \
              echo 'SLACK_CHANNEL_QA='${{ secrets.SLACK_CHANNEL_QA }} >> .env

      -   name: Execute script
          run: php bin/console slack:notifier

      -   name: Display cache for debugging
          run: cat .cache/slacknotifier_checkStatsQA.json

      -   name: Upload Stats for QA
          uses: actions/upload-artifact@v2
          with:
            name: slacknotifier_checkStatsQA
            path: .cache/slacknotifier_checkStatsQA.json